--CLEANING DATA IN SQL QUERIES
select *
from PORTFOLIO.DBO.DATACLEAN


--STANDARDIZING DATA FORMAT

select SaleconvertedTable, CONVERT(DATE, SaleDate)
from PORTFOLIO.DBO.DATACLEAN

UPDATE DATACLEAN
SET SaleDate=CONVERT(DATE, SaleDate)

ALTER TABLE DATACLEAN
Add SaleconvertedTable Date

UPDATE DATACLEAN
SET SaleconvertedTable = CONVERT(DATE, SaleDate)


--POPULATE PROPERTY ADDRESS DATA
SELECT A.ParcelID,A.PropertyAddress,B.ParcelID,B.PropertyAddress, ISNULL(A.PROPERTYADDRESS,B.PropertyAddress) AS NEWADDRESS
FROM DATACLEAN a
JOIN DATACLEAN b
ON A.[UniqueID ] = B.[UniqueID ]
AND A.ParcelID <> B.ParcelID
WHERE A.PropertyAddress IS NULL

UPDATE A
SET A.PropertyAddress = ISNULL(A.PROPERTYADDRESS,B.PropertyAddress)
FROM DATACLEAN A
JOIN DATACLEAN B
ON A.[UniqueID ] = B.[UniqueID ]
AND A.ParcelID <> B.ParcelID
WHERE A.PropertyAddress IS NULL


--BREAKING OUT ADDRESS INTO INDIVIDUAL COLUMNS
SELECT
SUBSTRING(PropertyAddress,1,CHARINDEX(',', PropertyAddress) -1) AS ADDRESS
FROM DATACLEAN

SELECT 
PARSENAME(REPLACE(OwnerAddress,',','.'), 3) AS STREET,
PARSENAME(REPLACE(OwnerAddress,',','.'), 2) AS CITY,
PARSENAME(REPLACE(OwnerAddress,',','.'), 1) AS CITYCODE
FROM DATACLEAN

ALTER TABLE DATACLEAN
ADD OWNERSTREET VARCHAR(50),OWNERCITY VARCHAR(50), CITYCODE VARCHAR(5)

UPDATE DATACLEAN
SET OWNERSTREET = PARSENAME(REPLACE(OwnerAddress,',','.'), 3), OWNERCITY=PARSENAME(REPLACE(OwnerAddress,',','.'), 2),
CITYCODE=PARSENAME(REPLACE(OwnerAddress,',','.'), 1)

SELECT [UniqueID ],OWNERSTREET,OWNERCITY,CITYCODE
FROM DATACLEAN


--CHANGE Y AND N TO YES AND NO IN THE SOLD AS VACANT COLUMN
SELECT DISTINCT(SoldAsVacant), COUNT(SoldAsVacant)
FROM DATACLEAN
GROUP BY SoldAsVacant
ORDER BY 1

UPDATE DATACLEAN
SET SoldAsVacant = CASE WHEN SoldAsVacant= 'Y' THEN 'YES'
				        WHEN SoldAsVacant= 'N' THEN 'NO'
					ELSE SoldAsVacant
					END

--REMOVE DUPLICATES

WITH ROWNUMBCTE AS (
SELECT *,
ROW_NUMBER() OVER (
PARTITION BY PARCELID,
			 PROPERTYADDRESS,
			 SALEDATE,
			 SALEPRICE
			 ORDER BY 
			 UNIQUEID)
			 ROW_NUM

FROM DATACLEAN
--ORDER BY PARCELID
)
SELECT * FROM ROWNUMBCTE 
WHERE ROW_NUM > 1
ORDER BY PropertyAddress


--REMOVE UNUSED COLUMNS
ALTER TABLE DATACLEAN
DROP COLUMN PROPERTYADDRESS, OWNERADDRESS,TAXDISTRICT

SELECT * 
FROM DATACLEAN
